-- MySQL Script generated by MySQL Workbench
-- Sun 29 Nov 2020 09:16:55 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema o3p_crm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema o3p_crm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `o3p_crm` DEFAULT CHARACTER SET utf8 ;
USE `o3p_crm` ;

-- -----------------------------------------------------
-- Table `o3p_crm`.`drzave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `o3p_crm`.`drzave` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `o3p_crm`.`mjesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `o3p_crm`.`mjesta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` TEXT NOT NULL,
  `postanski_broj` VARCHAR(20) NOT NULL,
  `drzave_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mjesta_drzave1_idx` (`drzave_id` ASC) VISIBLE,
  CONSTRAINT `fk_mjesta_drzave1`
    FOREIGN KEY (`drzave_id`)
    REFERENCES `o3p_crm`.`drzave` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `o3p_crm`.`adrese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `o3p_crm`.`adrese` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `ulica_broj` VARCHAR(45) NOT NULL,
  `ulica_broj_dodatak` VARCHAR(20) NULL,
  `grad_naselje` TEXT NULL,
  `drzava` TEXT NULL,
  `postanski_broj` VARCHAR(20) NULL,
  `rucni_unos` CHAR(1) NOT NULL,
  `mjesta_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_adrese_mjesta1_idx` (`mjesta_id` ASC) VISIBLE,
  CONSTRAINT `fk_adrese_mjesta1`
    FOREIGN KEY (`mjesta_id`)
    REFERENCES `o3p_crm`.`mjesta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `o3p_crm`.`razine_obrazovanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `o3p_crm`.`razine_obrazovanja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razina_obrazovanja_opis` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `o3p_crm`.`uloge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `o3p_crm`.`uloge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uloga_opis` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `o3p_crm`.`korisnici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `o3p_crm`.`korisnici` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `oib` CHAR(11) NOT NULL,
  `datum_rodenja` DATE NOT NULL,
  `spol_flag` CHAR(1) NOT NULL,
  `mobilni_telefon` VARCHAR(45) NULL,
  `fiksni_telefon` VARCHAR(45) NULL,
  `zanimanje` VARCHAR(45) NULL,
  `bracni_status_flag` CHAR(1) NULL,
  `prima_obavijesti_flag` CHAR(1) NULL,
  `zeli_aktivno_sudjelovati_flag` CHAR(1) NULL,
  `potvrdeno_clanstvo_flag` CHAR(1) NULL,
  `korisnicko_ime` VARCHAR(45) NULL,
  `lozinka_sol` VARCHAR(45) NULL,
  `lozinka_SHA256` VARCHAR(65) NULL,
  `email` VARCHAR(45) NULL,
  `datum_vrijeme_registracije` DATETIME NOT NULL,
  `napomena` TEXT NULL,
  `radni_interesi` TEXT NULL,
  `adrese_adresa_id` BIGINT(8) NOT NULL,
  `razine_obrazovanja_razina_obrazovanja_id` INT NULL,
  `uloge_uloga_id` INT NOT NULL,
  `korisnici_roditelj_1` BIGINT(8) NULL,
  `korisnici_roditelj_2` BIGINT(8) NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `korisnicko_ime_UNIQUE` (`korisnicko_ime` ASC) VISIBLE,
  UNIQUE INDEX `oib_UNIQUE` (`oib` ASC) VISIBLE,
  INDEX `fk_korisnici_adrese_idx` (`adrese_adresa_id` ASC) VISIBLE,
  INDEX `fk_korisnici_razine_obrazovanja1_idx` (`razine_obrazovanja_razina_obrazovanja_id` ASC) VISIBLE,
  INDEX `fk_korisnici_uloge1_idx` (`uloge_uloga_id` ASC) VISIBLE,
  INDEX `fk_korisnici_korisnici1_idx` (`korisnici_roditelj_1` ASC) VISIBLE,
  INDEX `fk_korisnici_korisnici1_idx1` (`korisnici_roditelj_2` ASC) VISIBLE,
  CONSTRAINT `fk_korisnici_adrese`
    FOREIGN KEY (`adrese_adresa_id`)
    REFERENCES `o3p_crm`.`adrese` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnici_razine_obrazovanja1`
    FOREIGN KEY (`razine_obrazovanja_razina_obrazovanja_id`)
    REFERENCES `o3p_crm`.`razine_obrazovanja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnici_uloge1`
    FOREIGN KEY (`uloge_uloga_id`)
    REFERENCES `o3p_crm`.`uloge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnici_korisnici_rod1`
    FOREIGN KEY (`korisnici_roditelj_1`)
    REFERENCES `o3p_crm`.`korisnici` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnici_korisnici_rod2`
    FOREIGN KEY (`korisnici_roditelj_2`)
    REFERENCES `o3p_crm`.`korisnici` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `o3p_crm`.`funkcionalnosti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `o3p_crm`.`funkcionalnosti` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `o3p_crm`.`razine_ovlasti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `o3p_crm`.`razine_ovlasti` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kodna_vrijednost` INT NOT NULL,
  `opis` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `o3p_crm`.`ovlasti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `o3p_crm`.`ovlasti` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `uloge_id` INT NOT NULL,
  `funkcionalnosti_id` INT NOT NULL,
  `razine_ovlasti_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  INDEX `fk_ovlasti_funkcionalnosti1_idx` (`funkcionalnosti_id` ASC) VISIBLE,
  INDEX `fk_ovlasti_razine_ovlasti1_idx` (`razine_ovlasti_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uloge_id_UNIQUE` (`uloge_id` ASC) VISIBLE,
  UNIQUE INDEX `funkcionalnosti_id_UNIQUE` (`funkcionalnosti_id` ASC) VISIBLE,
  CONSTRAINT `fk_ovlasti_uloge1`
    FOREIGN KEY (`uloge_id`)
    REFERENCES `o3p_crm`.`uloge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ovlasti_funkcionalnosti1`
    FOREIGN KEY (`funkcionalnosti_id`)
    REFERENCES `o3p_crm`.`funkcionalnosti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ovlasti_razine_ovlasti1`
    FOREIGN KEY (`razine_ovlasti_id`)
    REFERENCES `o3p_crm`.`razine_ovlasti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
